# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_occurrences <- function(vec) {
    .Call(`_runningEmu_count_occurrences`, vec)
}

